spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/real_estate_agency?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: testuser
    password: root
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: true
#      hibernate.jdbc.batch_size: 5
#      hibernate.order_inserts: true
#      hibernate.order_updates: true
#      hibernate.batch_versioned_data: true
---
jwttoken:
  secret: secret
  expire: 10000000